@startuml
scale 600 height
!include skatt.iuml
skinparam  BackgroundColor white



database DockerRegistry
database Nexus

storage  architect [
aurora/architect
---
1.8.0
]

storage flange [
aurora/flange
---
8.162.1
]


component BuildConfig [
BuildConfig
--
name=app
version=1.2.3
]


storage app [
app
---
latest
1
1.2
1.2.3
1.2.3-b1.8.0-flange-8.162.1
]

BuildConfig -down-> architect: use CustomBuilder
architect -up-> Nexus: fetch DeliveryBundle from
architect -right-> flange: FROM
architect --> app : produce

flange --> DockerRegistry: contains
architect --> DockerRegistry: contains
app -right-> DockerRegistry: pushed to
@enduml