@startuml
!include skatt.iuml
skinparam  BackgroundColor white

Jenkins<<ANNET>> -up-> [lage buildConfig, sette opp systemtest] AO
AO<<OS1>> -up-> [deploy, endre config]Boober<<AOS>>

Konsoll<<AOS>> --> [graphql] Gobo
Wallboard<<AOS>> -right-> [graphql] Gobo

Gobo<<AOS>> --> [AuroraApplication]Mokey<<AOS>>
Gobo --> [deploy]Boober<<AOS>>
Gobo -down-> [CRUD database]DatabaseHotell
Gobo -up->[Nettdebug] UncleMatt<<AOT>>
Gobo --> [tags, manifests] Cantus

Boober --> [CR skjema] DatabaseHotell<<AOS>>

Boober --> [vaults, auroraConfig, deploymentTags] Bitbucket<<ANNET>>
Boober --> [sts] Skap<<SITJ>>
Boober --> [ tagge release] Cantus
Boober --> OpenShift

Mokey<<AOS>> --> [applicationState]OpenShift
Prometheus<<AOT>> -->[scraper metrics APPLICATION_STATUS]Mokey

Icinga<<ANNET>> -down-> Gillis<<AOS>>
Icinga -down-> Gorg<<AOS>>
Gorg --> [ sletter temp miljø, app] OpenShift
Gillis --> [oppdatere STS cert] Boober
Cantus<<AOS>> --> [ hente tags, manifest] DockerRegistry

Clerk<<AOS>> -up-> [ hente pods, skalerer pods] OpenShift



@enduml