@startuml
scale 900 height
!include skatt.iuml
skinparam  BackgroundColor white


database DockerRegistry [
DockerRegistry
----
version: 1.3.0
]


component DeploymentConfig as DC

component IS [
ImageStream
---
version: 1
]

IS --> DC  : trigger deploy on new image

component ReplicationController as RC



component Pod [
Pod
---
name: app-2-xxx
]

DC -right-> RC: rollout app-2
RC -right-> Pod: start


storage app [
app
---
version=1.3.0
]

Pod -up-> app : contains

IS -right-> DockerRegistry: scheduled import

@enduml