@startuml
scale 600 height
!include skatt.iuml
skinparam  BackgroundColor white


file Build
database DockerRegistry
rectangle Doc
rectangle Sprocket
rectangle Cantus


database Kubernetes


Build --> DockerRegistry : 1. Push tag foo/bar:1
DockerRegistry -right-> Doc : 2. Audit event for foo/bar:1
Doc -->  Sprocket : 3. ImageChanged with sha abcd123
Sprocket --> Kubernetes: 4. find sprockets sha1-abc123
Sprocket --> Sprocket: 6. Partition and ratelimit
Sprocket -left-> Cantus : 5. Invalid cache for foo/bar:1
Sprocket -left-> Kubernetes : 7. Perform updates/builds/deploys









@enduml